spring.application.name=gestao-residuos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestao_residuos}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
server.servlet.context-path=/api
management.endpoint.health.show-details=when_authorized
management.endpoint.health.roles=ROLE_ADMIN
management.endpoints.web.exposure.include=health